kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
# ReadWriteOnce -> can be used by single node
# ReadOnlyMany -> Multiple nodes can read
# ReadWriteMany -> Can be read and writted to by many nodes
# https://kubernetes.io/docs/concepts/storage/storage-classes/
